// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NidusVision.Data;

#nullable disable

namespace NidusVision.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("NidusVision.Core.Models.AppSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("ConfidenceThreshold")
                        .HasColumnType("REAL");

                    b.Property<int>("DetectionRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GeneralRetentionDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InferenceEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("MaxStorageBytes")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SampleFps")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");
                });

            modelBuilder.Entity("NidusVision.Core.Models.Camera", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("MainRtspUrl")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordProtected")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoiJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubRtspUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Transport")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Cameras");
                });

            modelBuilder.Entity("NidusVision.Core.Models.DetectionEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BoundingBoxJson")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("TEXT");

                    b.Property<float>("Confidence")
                        .HasColumnType("REAL");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SegmentIdsJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ThumbnailPath")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Confidence");

                    b.HasIndex("CameraId", "StartUtc");

                    b.ToTable("DetectionEvents");
                });

            modelBuilder.Entity("NidusVision.Core.Models.LocalUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocalUsers");
                });

            modelBuilder.Entity("NidusVision.Core.Models.RecordingSegment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ByteSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CameraId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Codec")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasHuman")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CameraId", "StartUtc");

                    b.HasIndex("HasHuman", "EndUtc");

                    b.ToTable("RecordingSegments");
                });

            modelBuilder.Entity("NidusVision.Core.Models.DetectionEvent", b =>
                {
                    b.HasOne("NidusVision.Core.Models.Camera", "Camera")
                        .WithMany("Detections")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("NidusVision.Core.Models.RecordingSegment", b =>
                {
                    b.HasOne("NidusVision.Core.Models.Camera", "Camera")
                        .WithMany("Segments")
                        .HasForeignKey("CameraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Camera");
                });

            modelBuilder.Entity("NidusVision.Core.Models.Camera", b =>
                {
                    b.Navigation("Detections");

                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
